name: vassoura
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies: 
  mime: ^1.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
