name: vassoura
description: Find which files are gathering dust and make your project cleaner
version: 0.0.1
homepage: https://github.com/Ascenio/vassoura
repository: https://github.com/Ascenio/vassoura
issue_tracker: https://github.com/Ascenio/vassoura/issues

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  args: ^2.1.0
  collection: ^1.15.0
  meta: ^1.3.0
  mime: ^1.0.0
  path: ^1.8.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4

vas: vassoura
